Mtf finetuning
bigscience-workshop/Megatron-DeepSpeed pull request #288
Opened 2022-06-22 10:43 UTC by lintangsutawika

This is the multitask-finetuning part @thomasw21

2022-06-22 12:04 UTC, thomasw21 commented on train_ND_MTF_gpt.py
> +# coding=utf-8
I'd rather have this in another PR. I really only want to merge `non_causal_mtf_dataset.py` in this PR + test on that dataloder, if that's alright.

2022-06-22 12:28 UTC, lintangsutawika commented on train_ND_MTF_gpt.py
> +# coding=utf-8
Right, i've removed scripts besides `non_causal_mtf_dataset.py` and reverted `arguments.py` and `tokenizer.py`

2022-06-23 23:23 UTC, thomasw21 reviewed
Very high level review, I think it sounds like a good plan currently. Let me know if you need help implementing things.

2022-06-23 23:23 UTC, thomasw21 commented on tests/data/t0/ag_news_classify_question_first.json
> +{"text": "What label best describes this news article?\nWall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green agai
Feel free to upload this dataset on the hub, and load from there.

2022-06-23 23:23 UTC, thomasw21 commented on tests/data/t0/ag_news_classify_question_first.json
> +{"text": "What label best describes this news article?\nWall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green agai
I also think you should just keep `inputs` and `targets` and tweak the preprocessing script in order to return `{tokenized_inputs} {impossible_token_id} {tokenized_targets}`.

2022-06-23 23:23 UTC, thomasw21 commented on megatron/data/data_samplers.py
> +            if len(batch) == self.micro_batch_size:
I'm guessing the packing changes this condition, ie you need some sort of access to the sequence length of each sample.

2022-06-23 23:23 UTC, thomasw21 commented on megatron/data/non_causal_mtf_dataset.py
> +            sample_idx = helpers.build_sample_idx(sizes, doc_idx, seq_length,
I don't think we want this as documents now vary in size. So now you probably want to truncate to the right is samples are too big instead of wrapping them.

2022-06-23 23:23 UTC, thomasw21 commented on megatron/data/non_causal_mtf_dataset.py
> +                                             sample_idx.shape[0] - 1, np_rng)
We should have a document shuffling.

2022-06-23 23:23 UTC, thomasw21 commented on megatron/data/non_causal_mtf_dataset.py
> +        eod_idx = np.where(sample == self.tokenizer.eod)[0]
Yeah I really want to change this condition to something else ...

2022-06-23 23:23 UTC, thomasw21 commented on megatron/data/non_causal_mtf_dataset.py
> +        )
```suggestion
        sample = self.indexed_dataset.get(
            self.doc_idx[idx]
        )
```
Shouldn't it be this instead?

2022-06-23 23:23 UTC, thomasw21 commented on megatron/data/non_causal_mtf_dataset.py
> +    shuffle_idx_filename = _filename + '_shuffle_idx.npy'
I'd suggest adding a `mtf` mention to not overwrite otherdatasets.

2022-06-24 01:36 UTC, lintangsutawika commented on megatron/data/non_causal_mtf_dataset.py
> +    shuffle_idx_filename = _filename + '_shuffle_idx.npy'
Something like this maybe?
```
doc_idx_filename = _filename + '_mtf_doc_idx.npy'
sample_idx_filename = _filename + '_mtf_sample_idx.npy'
shuffle_idx_filename = _filename + '_mtf_shuffle_idx.npy'
```

2022-06-24 06:25 UTC, lintangsutawika commented on tests/data/t0/gpt2-tiny-merges.txt
> +#version: 0.2 - Trained by `huggingface/tokenizers`
Removed

2022-06-24 06:27 UTC, lintangsutawika commented on megatron/data/data_samplers.py
> +            if len(batch) == self.micro_batch_size:
Yes, I think I will need to add the dataset directly into the data loader.

2022-06-24 06:31 UTC, lintangsutawika commented on megatron/data/non_causal_mtf_dataset.py
> +            sample_idx = helpers.build_sample_idx(sizes, doc_idx, seq_length,
Should I replace 
```
# Use C++ implementation for speed.
# First compile and then import.
from megatron.data import helpers
assert doc_idx.dtype == np.int32
assert sizes.dtype == np.int32
sample_idx = helpers.build_sample_idx(sizes, doc_idx, seq_length,
    num_epochs, tokens_per_epoch)
```
With this?
```
sample_idx = random.sample(doc_idx, len(doc_idx))
```

2022-06-24 06:35 UTC, lintangsutawika commented on megatron/data/non_causal_mtf_dataset.py
> +                                             sample_idx.shape[0] - 1, np_rng)
Should I replace it with this?
```
sample_idx = random.sample(doc_idx, len(doc_idx))
```

2022-06-24 06:39 UTC, lintangsutawika commented on megatron/data/non_causal_mtf_dataset.py
> +        eod_idx = np.where(sample == self.tokenizer.eod)[0]
I changed it to 
```
        eod_idx = np.where(sample == self.impossible_token)[0]
```

It doesn't need tokenizer anymore.

2022-06-29 11:49 UTC, Muennighoff commented on pretrain_t0.py
> +    #             eval(f"{s}_ds").append(d)
I think we can also support this one, no?
This is the one we used for the 176B training & probably the one we want to use for MTF

2022-06-29 12:04 UTC, thomasw21 commented on pretrain_t0.py
> +    #             eval(f"{s}_ds").append(d)
Dunno, we probably want a single dataset and not play with weights ... why do you think we need to have weights?

2022-06-29 13:49 UTC, Muennighoff commented on examples/finetune_t0.sh
> +       }"
What about expecting the user to provide the data in the form
`input_document target_document input_document2 target_document2...`?
And then we turn it into `[[input_doc, target_doc], [input_doc2, target_doc2] ...`.
Will open a PR for this if you agree

2022-06-29 14:18 UTC, lintangsutawika commented on examples/finetune_t0.sh
> +       }"
Not sure. I think it's important we future-proof it, but currently for Bloom-Zero the above should suffice. 

Also, what about this?
```
DATA_PATH="{ \
        'input_tokens': ['input_document_0', 'input_document_1', ...] ,  \
       'target_tokens': ['target_document_0', 'target_document_1', ...]  \
       }"
```

2022-06-29 14:53 UTC, Muennighoff commented on examples/finetune_t0.sh
> +       }"
The problem is `--data-path` turns the above into a list based on spaces, i.e. `["{", "'input_tokens':", ..]`, so we would need a new argument that leaves it as a string & then load this in via json.

2022-06-29 16:16 UTC, lintangsutawika commented on examples/finetune_t0.sh
> +       }"
Hmmm, I see, my understanding was that it would be a single string line which can be parsed like this
```
    if args.data_path:

        import json
        data_path_dict = [json.loads(args.data_path)]

        train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
            data_prefix=args.data_path,
            data_impl=args.data_impl,
            splits_string=args.split,
            train_valid_test_num_samples=train_val_test_num_samples,
            seq_length=args.seq_length,
            seed=args.seed,
            skip_warmup=(not args.mmap_warmup))
```

2022-06-29 16:20 UTC, thomasw21 commented on examples/finetune_t0.sh
> +       }"
yeah I think the API is much cleaner. you can alway have the same prefix and have the dataset find "_inputs" and "_targets" as suffix. (in GPTDataset you'll see that there's a bunch of files)

2022-06-30 11:00 UTC, thomasw21 requested changes
Blocking so we don't accidentally merge this into `master`. I'm working on another branch and slowly incorporating the changes.

2022-06-30 11:03 UTC, lintangsutawika commented
Should I change the merge direction to another branch instead of main?

2022-06-30 11:07 UTC, thomasw21 commented
No it's all good.

2022-07-07 14:17 UTC, thomasw21 commented
Closing as we've merged the other branches

2022-07-07 14:17 UTC, closed without merging