Add generation server scripts using HF accelerate and DS-inference
bigscience-workshop/Megatron-DeepSpeed pull request #328
Opened 2022-08-11 08:04 UTC by mayank31398

Currently, the scripts are working correctly.
However, there is some memory leak.
In https://github.com/huggingface/accelerate/issues/614 @sgugger says that its not in accelerate which is probably true.

My hunch is a related bug: https://github.com/apache/incubator-mxnet/issues/19159

2022-08-11 08:04 UTC, mayank31398 commented
This is still WIP
@stas00

2022-08-11 18:28 UTC, stas00 reviewed
thank you for working on refactoring and the server code, @mayank31398 

1. let's create libraries rather than having direct scripts importing from the server scripts, so both types import the same library. So probably the following structure:

```
bloom-inference-accelerate.py            # library sharing code
bloom-inference-accelerate-cli.py       # the original script importing from bloom-inference-accelerate.py
bloom-inference-accelerate-server.py # the server script importing from bloom-inference-accelerate.py
```

same for other sets.

This is of course just a suggestion, I'm happy to hear other ideas.

2022-08-11 18:28 UTC, stas00 commented on scripts/inference/README.md
> +To run a server using HuggingFace (requires [accelerate](https://github.com/huggingface/accelerate) to be installed):
let's add it after the existing doc since most users will want the non-server solutions first and please add a header:

`## Inference on Server`

or something like that. before the new section

2022-08-16 22:17 UTC, mayank31398 commented
@stas00, I believe the code is in good shape. You can start reviewing.
Also, I'll start updating the README for instructions tomorrow

2022-08-16 22:51 UTC, mayank31398 commented
Hmm, also the build crashed due to non-availability of compute here @stas00 ^^

2022-08-17 17:47 UTC, stas00 commented on inference/cli.py
> +        ],
where did DS-ZeRO go?

2022-08-17 17:56 UTC, stas00 commented
Oh wow, you developed a whole package around this. Impressive work, @mayank31398 

Let's just discuss the user-facing APIs before implementing to minimize wasting time.

Originally, these were just scripts to benchmark and demo how the various solutions can be used, but now I'm not so sure how demo-friendly these are. 

Some design questions
- Why does CLI import from the server code?
- would it really make things simpler to have one cli script for all the different systems? they are quite different after all with very different arguments - e.g. ds-zero will need `nvmi` path as well and flags for cpu/nvme offload?
- the while loop in `cli.py` isn't debug friendly - can we activate it only with an explicit flag, but by default just use a ready inputs
- multiple input BS>1 functionality got lost in transition
- naming of the scripts lost their mnemonics - `cli.py` is very ambiguous since it tells me nothing of what it does. Please see my suggestions at https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/328#pullrequestreview-1070168477

I'm also no longer sure what to do with this package. Originally the plan was to stash it under transformers' research files, but now it's growing towards an independent package. Not a bad thing, I'm just thinking aloud.

2022-08-17 19:00 UTC, mayank31398 commented on inference/cli.py
> +        ],
Currently, DS-ZeRO is not added in CLI.
Do we want to?
Since the latency for a single batch is really high.
I have added that in benchmark script only.

2022-08-17 19:11 UTC, mayank31398 commented
1. I found it easier to deploy using DeepSpeed-MII and leverage that for CLI. But I wan't really sure of the overhead it causes, so still using the barebones DS-inference for benchmarking. Using DeepSpeed-MII lets me get away with doing broadcast operation of the input. Also, for code modification (if required down the line), this might be simpler.
2. I am not sure if we should add DS-ZeRO to CLI. The latency for me (batch size = 1 and output tokens = 100) is 23 sec for accelerate, 7 sec for DS-inference and 230 sec for DS-ZeRO. So, it doesn't make sense to add that. Its nice to have it in benchmarking though.
3. I think adding a --input_file flag to cli script might be useful. If not provided, we can launch in interactive mode. I will try to make this debug friendly. Currently, it crashes.
4. batch_size > 1 still works, in both server mode and benchmark script. Not in CLI (since I am expecting user to input via command line for now).
5. I was having trouble with the naming convention (because of hyphens in name, couldn't import packages). We can rename cli to interactive or something.

Let me know your thoughts on this

2022-08-17 19:16 UTC, mayank31398 commented
Also, I am not sure if this works for other models (a few strings are hardcoded). I think for now we should stick to BLOOM.
I can open up another PR to support other models.
Adding so much functionality in a single PR might not be the best thing to do.

2022-08-17 19:32 UTC, stas00 commented on inference/cli.py
> +        ],
yes, but it supports cpu/nvme offload, slow but working for someone w/o many large gpus.

I think accelerate supports that too, with a slower performance as well.

2022-08-17 20:55 UTC, mayank31398 commented
> you don't need to broadcast anything for non-server usage. It sounds like you built `cli.py` as a client to the server, but that's too complicated for someone who just wants to process a few inputs.

cli works this way. The user only needs to provide input_text. Also, I need to call generate method on all 8 GPU processes (in non-server usage), and since the input text will only be requested on 1 process. You need to broadcast it as far as I understand.

> Perhaps we have miscommunicated here.

benchmark supports all 3 frameworks
cli and server only support accelerate and ds-inference. Didn't see need of ZeRO since its too slow.

I will incorporate your suggestions.

2022-08-17 20:56 UTC, mayank31398 commented
So, just to summarize for cli.py:
You want the option for user to provide an input text file?

2022-08-17 21:04 UTC, mayank31398 commented
Also, @stas00 , I am fine with both. If we want, we can keep this branch as a separate branch if users want to leverage a standalone system.
What do you think?

2022-08-17 21:58 UTC, stas00 commented
branch, no, as branches are hard to keep in sync - and especially since we will move it out of Meg-DS anyway once you're done . I propose let's create 2 sub-folders 

1. one for the straight scripts - i.e. move the current ones instead of deleting those.
2. another for your sophisticated set up - and there you don't need to support ZeRO at all. And you can leave everything as it is now in this PR. 

I think that would allow meeting different use cases w/o getting in the way of each other.

I know I was the one who proposed to refactor to support your server work, but now I can see that keeping both versions is probably the simplest design choice.

2022-08-17 22:00 UTC, stas00 commented
> So, just to summarize for cli.py: You want the option for user to provide an input text file?

If we keep the original scripts as they there are I think we can keep your version as it is for now w/o any cmd args changes. If someone asks for it it can be added later.

2022-08-18 07:16 UTC, mayank31398 commented
Thanks for the comments Stas. Will incorporate the changes

I have added back the older scripts in scripts/inference folder (original path).
Will update README.md

2022-08-19 16:02 UTC, stas00 commented
> I have added back the older scripts in scripts/inference folder (original path).

and let's move the 2 solutions to their respective sub-dirs:
```
bloom-inference-scripts
bloom-inference-server
```

we don't want them to be together, as it'd be difficult to understand quickly.

thank you, @mayank31398

2022-08-19 17:34 UTC, mayank31398 commented
> > I have added back the older scripts in scripts/inference folder (original path).
> 
> and let's move the 2 solutions to their respective sub-dirs:
> 
> ```
> bloom-inference-scripts
> bloom-inference-server
> ```
> 
> we don't want them to be together, as it'd be difficult to understand quickly.
> 
> thank you, @mayank31398

I assume these 2 folders should be located inside scripts/   ?

2022-08-19 17:38 UTC, stas00 commented
yes, please.

2022-08-20 11:15 UTC, mayank31398 commented
Done. Added README too @stas00

2022-08-21 19:48 UTC, mayank31398 commented
New commit in DeepSpeed master branch causes breaking changes.
https://github.com/microsoft/DeepSpeed/pull/2132#issuecomment-1221592051
Waiting for a fix @RezaYazdaniAminabadi

2022-08-22 23:57 UTC, stas00 commented
Looks great, @mayank31398 - thank you!

I need to think how I could test the functionality. Probably might work from the local client on the same host (as the node I have access to has no outside access).

2022-08-23 00:13 UTC, mayank31398 commented
I see @stas00 
I have a script that does that for you. Are you saying the node you have can only be accessed from a login node or something?
If that is how your setup is, I have a similar setup. Our compute nodes have no outside access, only the login node.
If I am misunderstanding the probem, ignore this :trollface: 
I use the following script to test from my local machine:

```python
from sshtunnel import SSHTunnelForwarder
import http
import requests
import paramiko
​
​
class BloomServer:
    
    def __init__(self, bloom_ip="<IP HERE>", bloom_port=<PORT HERE>, relative_path="/generate/",
                 private_key_path = "<PATH TO ID_RSA>"): 
        
        pkey = paramiko.RSAKey.from_private_key_file(private_key_path)
        self.remote_host = "<PATH TO LOGIN NODE>"
        self.remote_user = "<USERNAME>"
        self.remote_port = <PORT FOR LOGIN NODE>
        self.bloom_ip = bloom_ip
        self.bloom_port = bloom_port
        self.server = SSHTunnelForwarder(
                ssh_address_or_host=self.remote_host,
                ssh_username=self.remote_user,
                ssh_private_key=pkey,
                remote_bind_address=(self.bloom_ip, self.bloom_port),
                ) 
        self.server.skip_tunnel_checkup = False
        self.server.start()
        self.server.check_tunnels()
        print(self.server.tunnel_is_up, flush=True)
        
        server_local_url =  "127.0.0.1:" + str(self.server.local_bind_address[1])
        self.local_url = "http://" + server_local_url + relative_path
​
    def get_response(self, prompt, max_new_tokens=10, temperature=0.):
        min_length = "1"
        max_length = "10"
        max_new_tokens = str(max_new_tokens)
        top_k = "5"
        top_p =  "1"
        temperature = str(temperature)
        request_body = {
            "input_text": prompt,
            "min_length": min_length,
            "max_length": max_length,
            "top_p": top_p,
            "top_k":top_k,
            "temperature": temperature,
            "max_new_tokens": max_new_tokens,
            "return_type": "output_only"
        }
        try:
            response = requests.post(self.local_url, json=request_body, verify=False)
            return response.json(), "OK"
        except:
            return {}, "failed"
​
​
if __name__=="__main__":
    server = BloomServer()
    prompt = "I need some help with the"
    output = server.get_response(prompt)
    print("Prompt:", prompt)
    print("Output", output)
```

2022-08-23 01:21 UTC, mayank31398 commented
Also, switching from Flask to Starlette + FastAPI fixed the memory leak.

2022-08-23 11:46 UTC, mayank31398 commented
@stas00 https://github.com/huggingface/accelerate/issues/614#issuecomment-1223950292
Memory is still leaking in accelerate even with this minimal working example.

2022-08-23 16:42 UTC, stas00 commented
so is there a memory leak still or not? You shared there still was but then removed the comment.

If there is we should try to isolate it - by first identifying whether it's in `accelerate` or the `transformers` modeling code by simply repeating the generate call.

2022-08-23 17:09 UTC, mayank31398 commented
> 

So, i don't really think its a memory leak @stas00 
https://github.com/huggingface/accelerate/issues/614
I want to look more into this.

THis is what I plan to do: https://github.com/huggingface/accelerate/issues/614#issuecomment-1224285433
Should give us an idea of whether things are good to go or not.

2022-08-23 17:10 UTC, mayank31398 commented
For now, I will investigate this further.
Lets not merge this PR yet :)

2022-08-23 23:43 UTC, stas00 commented
It looks like the `transformers` internal APIs have changed and the old code no longer works. Here is the new drop in replacement:

```
from pathlib import Path
from transformers.utils import is_offline_mode
from huggingface_hub import snapshot_download

def get_checkpoint_files(model_name_or_path, revision=None):
    # checks if online or not
    if is_offline_mode():
        print("Offline mode: forcing local_files_only=True")
        local_files_only = True
    else:
        local_files_only = False

    # loads files from hub
    cached_repo_dir = snapshot_download(model_name_or_path, allow_patterns=["*"], local_files_only=local_files_only, revision=revision)

    # creates a list of paths from all downloaded files in cache dir
    file_list = [str(entry) for entry in Path(cached_repo_dir).rglob('*.pt') if entry.is_file()]
    return file_list
```

you should be able to use it if you update your `transformers` clone to the the latest.

credits: @philschmid

2022-08-23 23:57 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +1. [HuggingFace accelerate](https://github.com/huggingface/accelerate)
let's make the easily installable ones into that:
```
pip install deepspeed accelerate huggingface_hub>=0.9.0
```

add the minimal versions if needed

2022-08-24 00:20 UTC, stas00 commented
when I run:

```
python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype bf16 --deployment_framework hf_accelerate --generate_kwargs '{"min_length": 100, "max_new_tokens": 100, "do_sample": false}'
```

the first input went ok, but when it returned it messed things up:

```
Loading model...
Model loaded
Input text: whoah!
change generate_kwargs? [y/n] y
Generate kwargs: {"min_length": 100, "max_new_tokens": 100, "do_sample": false}

Output text: whoah!"

"What's the matter?" asked the other.

"Matter?" repeated the first. "Why, I thought I heard a shot."

"So did I," said the other. "But it was only a gun."

"Only a gun!" exclaimed the first. "Then it must have been a gun."

"It was," said the other. "But it was only a gun."

"Only a gun!" repeated
Generated tokens: 100
Input text: change generate_kwargs? [y/n]
```

as you can see the last line it mixed 2 inputs together? 

I think it's because I was impatient and entered 'Enter' at some point.

but it shouldn't allow an empty prompt, should it?

Perhaps it should consume all inputs before generating a new prompt, so that only the response to the prompt is used?

2022-08-24 00:24 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
I'd say make `--save_mp_checkpoint_path <PATH TO DS CACHED MODEL>` optional - why save it every time?

and list it as an option below for those who want it - and also how to load it after it was saved of course.

2022-08-24 00:26 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
have you tried running this one? I run into multiple issues here:

```
python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path cache --generate_kwargs '{"min_length": 100, "max_new_tokens": 100, "do_sample": false}'
Traceback (most recent call last):
  File "scripts/bloom-inference-server/cli.py", line 80, in <module>
    main()
  File "scripts/bloom-inference-server/cli.py", line 44, in main
    model = DSInferenceGRPCServer(args)
  File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/Megatron-DeepSpeed/scripts/bloom-inference-server/ds_inference/grpc_server.py", line 16, in __init__
    files = os.listdir(args.save_mp_checkpoint_path)
FileNotFoundError: [Errno 2] No such file or directory: 'cache'
```

```
mkdir cache
python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path cache --generate_kwargs '{"min_length": 100, "max_new_tokens": 100, "do_sample": false}'
Traceback (most recent call last):
  File "scripts/bloom-inference-server/cli.py", line 80, in <module>
    main()
  File "scripts/bloom-inference-server/cli.py", line 44, in main
    model = DSInferenceGRPCServer(args)
  File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/Megatron-DeepSpeed/scripts/bloom-inference-server/ds_inference/grpc_server.py", line 23, in __init__
    if ("base_dir" in checkpoints_json):
UnboundLocalError: local variable 'checkpoints_json' referenced before assignment
```

2022-08-24 01:08 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +```shell
missing instructions to install 

```
pip install fastapi
```

2022-08-24 01:17 UTC, stas00 requested changes

2022-08-24 01:17 UTC, stas00 commented on scripts/bloom-inference-server/examples/server_request.py
> +    print(response.json())
```suggestion
    print(response.json(), "\n")
```
let's make the output a little bit more user-friendly out of the box.

2022-08-24 01:17 UTC, stas00 commented on scripts/bloom-inference-server/examples/server_request.py
> +    print(response.json())
```suggestion
    print(response.json(), "\n")
```

2022-08-24 01:30 UTC, stas00 commented
The DS-inference server crashes for me w/o the cached tp checkpoint


```
deepspeed --num_gpus 8 scripts/bloom-inference-server/benchmark.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference  --benchmark_cycles 5
[...]
Traceback (most recent call last):
  File "scripts/bloom-inference-server/benchmark.py", line 188, in <module>
    main()
  File "scripts/bloom-inference-server/benchmark.py", line 179, in main
    benchmark_end_to_end(args, DSInferenceModel)
  File "scripts/bloom-inference-server/benchmark.py", line 75, in benchmark_end_to_end
    model, initialization_time = run_and_log_time(
  File "scripts/bloom-inference-server/benchmark.py", line 37, in run_and_log_time
    results = execs()
  File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/Megatron-DeepSpeed/scripts/bloom-inference-server/utils/utils.py", line 30, in __call__
    return self.func(**self.kwargs)
  File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/Megatron-DeepSpeed/scripts/bloom-inference-server/ds_inference/model.py", line 57, in __init__
    self.model = deepspeed.init_inference(
  File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/DeepSpeed/deepspeed/__init__.py", line 293, in init_inference
    engine = InferenceEngine(model,
  File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/DeepSpeed/deepspeed/inference/engine.py", line 154, in __init__
    self.module.to(device)
  File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

2022-08-24 03:46 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +1. [HuggingFace accelerate](https://github.com/huggingface/accelerate)
DeepSpeed needs to be at master branch.
pip install is not up-do-date yet.

2022-08-24 03:49 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
@stas00 . The caching is not done every time. I think the argument name is misleading. I will change that.
Yeah if the directory already exists but is empty, it leads to an error. Thanks for pointing this out.

2022-08-24 03:50 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
For caching, one needs to run cache_ds_checkpoints. Will change argument name here

2022-08-24 03:52 UTC, mayank31398 commented
> The DS-inference server crashes for me w/o the cached tp checkpoint
> 
> ```
> deepspeed --num_gpus 8 scripts/bloom-inference-server/benchmark.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference  --benchmark_cycles 5
> [...]
> Traceback (most recent call last):
>   File "scripts/bloom-inference-server/benchmark.py", line 188, in <module>
>     main()
>   File "scripts/bloom-inference-server/benchmark.py", line 179, in main
>     benchmark_end_to_end(args, DSInferenceModel)
>   File "scripts/bloom-inference-server/benchmark.py", line 75, in benchmark_end_to_end
>     model, initialization_time = run_and_log_time(
>   File "scripts/bloom-inference-server/benchmark.py", line 37, in run_and_log_time
>     results = execs()
>   File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/Megatron-DeepSpeed/scripts/bloom-inference-server/utils/utils.py", line 30, in __call__
>     return self.func(**self.kwargs)
>   File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/Megatron-DeepSpeed/scripts/bloom-inference-server/ds_inference/model.py", line 57, in __init__
>     self.model = deepspeed.init_inference(
>   File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/DeepSpeed/deepspeed/__init__.py", line 293, in init_inference
>     engine = InferenceEngine(model,
>   File "/gpfsssd/worksf/projects/rech/six/commun/code/inference/DeepSpeed/deepspeed/inference/engine.py", line 154, in __init__
>     self.module.to(device)
>   File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
>     return self._apply(convert)
>   File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
>     module._apply(fn)
>   File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
>     param_applied = fn(param)
>   File "/gpfswork/rech/six/commun/conda/inference/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
>     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
> NotImplementedError: Cannot copy out of meta tensor; no data!
> ```

This is a bug in deepspeed:  https://github.com/microsoft/DeepSpeed/pull/2132#issuecomment-1221592051

2022-08-24 04:00 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
Also, the backend for this is running via DeepSpeed MII.
Which requires re-sharded checkpoints.

2022-08-24 07:00 UTC, mayank31398 commented
I feel like empty prompt is fine. This is basically unconditional generation right?
I will try to fix the keyboard interrupt.

2022-08-24 18:07 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
none of this will be needed in a bit, as we now have https://huggingface.co/microsoft/bloom-deepspeed-inference-fp16 so it's already pre-sharded and can be used directly - just sorting out the naming of the files, so please wait just a bit before this is settled.

2022-08-24 20:23 UTC, stas00 commented
> I feel like empty prompt is fine. This is basically unconditional generation right?

Good question - I have never tried it - I guess it should work.

2022-08-24 22:32 UTC, mayank31398 commented
Also, @stas00 I have been meaning to ask.
Is accelerate using DeepSpeed ZeRO as its backend?
Because if that is the case then the generation time per batch for both of them differ greatly right?

2022-08-24 23:00 UTC, stas00 commented
> Is accelerate using DeepSpeed ZeRO as its backend?

It can but it's not using it in our scripts here. It uses a naive pipeline parallelism, assigning different layers to different devices and switching between those.

2022-08-25 00:14 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +1. [HuggingFace accelerate](https://github.com/huggingface/accelerate)
that's easy, 

```
pip install git+https://github.com/microsoft/DeepSpeed
```

2022-08-25 00:15 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +1. [HuggingFace accelerate](https://github.com/huggingface/accelerate)
and you can already make a note of which minimal version will be required - i.e. the next released one - that way you don't have to search for it later. (if it makes sense that is)

2022-08-25 00:16 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +1. [HuggingFace accelerate](https://github.com/huggingface/accelerate)
so something like:

```
pip install git+https://github.com/microsoft/DeepSpeed accelerate huggingface_hub>=0.9.0
# use deepspeed==0.7.2 when it's released.
```

2022-08-25 00:23 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
Is it working right now?
I think I will wait, since that will drop the need for https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/328#issuecomment-1224997559

2022-08-25 00:33 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
Yes, here is a slightly modified version of the original script:

[bloom-ds-inference-tp-sharded.txt](https://github.com/bigscience-workshop/Megatron-DeepSpeed/files/9420261/bloom-ds-inference-tp-sharded.txt)

```
# run int8 inference
deepspeed --num_gpus 8 scripts/inference/bloom-ds-inference-tp-sharded.py --name microsoft/bloom-deepspeed-inference-int8 --dtype int8 --batch_size 1

# run fp16 inference
deepspeed --num_gpus 8 scripts/inference/bloom-ds-inference-tp-sharded.py --name microsoft/bloom-deepspeed-inference-fp16 --dtype float16 --batch_size 1
```

You'd need to be on this branch: https://github.com/microsoft/DeepSpeed/pull/2217

2022-08-26 19:51 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
generate_kwargs = {'min_length': 100, 'max_new_tokens': 100, 'do_sample': False}
batch_size = 1
------------------------------------------------------------
in = DeepSpeed is a machine learning framework
out = DeepSpeed is a machine learning frameworkRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTCRTC
This is the output for me for int8 model

2022-08-27 10:33 UTC, mayank31398 commented
@stas00 , while working on this, found a really interesting [bug](https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/335). **Could be a severe one**.
I have provided a minimal working example.

2022-08-28 02:30 UTC, mayank31398 commented
> from huggingface_hub import snapshot_download
1. I am still using the old method (it is still working for >=0.9.0) if the user inputs the model_name as bigscience/bloom in ds-inference. I am doing this because snapshot _download is not respecting the TRANSFORMERS_CACHE and I don't want it to download duplicate checkpoints (for bigscience/bloom). However, this is slow (reshards the 72 files)
1. For the newer weights provided by microsoft, I am using snapshot_download. Also, I am adding support for int8 as well in this PR. However, this is much faster.

I feel like this is the best approach for now. If we want to change this we can do that in a separate PR in the future.

@stas00

2022-08-28 02:46 UTC, stas00 commented
> because snapshot _download is not respecting the TRANSFORMERS_CACHE

If you use `HUGGINGFACE_HUB_CACHE` instead of `TRANSFORMERS_CACHE` it would work for either.

Alternatively you can do:
```
HUGGINGFACE_HUB_CACHE = os.getenv("HUGGINGFACE_HUB_CACHE", None)
cache_dir =  = os.getenv("TRANSFORMERS_CACHE", HUGGINGFACE_HUB_CACHE)
snapshot_download(..., cache_dir=cache_dir)
```

If neither is set, `None` would lead to the default path.

You can see:

https://github.com/huggingface/transformers/blob/21f6f58721dd9154357576be6de54eefef1f1818/src/transformers/utils/hub.py#L92

2022-08-28 02:54 UTC, mayank31398 commented
> > because snapshot _download is not respecting the TRANSFORMERS_CACHE
> 
> If you use `HUGGINGFACE_HUB_CACHE` instead of `TRANSFORMERS_CACHE` it would work for either.
> 
> Alternatively you can do:
> 
> ```
> HUGGINGFACE_HUB_CACHE = os.getenv("HUGGINGFACE_HUB_CACHE", None)
> cache_dir =  = os.getenv("TRANSFORMERS_CACHE", HUGGINGFACE_HUB_CACHE)
> snapshot_download(..., cache_dir=cache_dir)
> ```
> 
> If neither is set, `None` would lead to the default path.
> 
> You can see:
> 
> https://github.com/huggingface/transformers/blob/21f6f58721dd9154357576be6de54eefef1f1818/src/transformers/utils/hub.py#L92

Ok, so if I understand correctly, what you are saying is that I don't need to set TRANSFORMERS_CACHE?
Just setting HUGGINGFACE_HUB_CACHE should be enough?

2022-08-28 06:44 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
This has been fixed. Was a bug in DeepSpeed. Thanks @RezaYazdaniAminabadi

2022-08-28 16:05 UTC, stas00 commented
Actually, the first line isn't needed, as it's already the default:
https://github.com/huggingface/huggingface_hub/blob/7aadc3243d9478a48e17f568d8d4950cafd11ca2/src/huggingface_hub/_snapshot_download.py#L103-L104

so just:

```
cache_dir =  = os.getenv("TRANSFORMERS_CACHE", None)
snapshot_download(..., cache_dir=cache_dir)
```

2022-08-28 23:21 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
@stas00 , I noticed that we are creating the dummy tensors using deepspeed.OnDevice(dtype=torch.float16) on line 167. Shouldn't we change this to int8 for qunatization?
I m getting throughput = 89msec/token for 8 and 160msec/token for 8 and 4 GPUs respectively. Can this ^^ be the reason?

2022-08-29 02:02 UTC, mayank31398 commented
DeepSpeed-MII not working with new Microsoft weights: https://github.com/microsoft/DeepSpeed-MII/issues/50

2022-08-30 01:45 UTC, pai4451 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
> Yes, here is a slightly modified version of the original script:
> 
> [bloom-ds-inference-tp-sharded.txt](https://github.com/bigscience-workshop/Megatron-DeepSpeed/files/9420261/bloom-ds-inference-tp-sharded.txt)
> 
> it just collects the repo files in a different way and handles int8 as well.
> 
> ```
> # run int8 inference
> deepspeed --num_gpus 8 scripts/inference/bloom-ds-inference-tp-sharded.py --name microsoft/bloom-deepspeed-inference-int8 --dtype int8 --batch_size 1
> 
> # run fp16 inference
> deepspeed --num_gpus 8 scripts/inference/bloom-ds-inference-tp-sharded.py --name microsoft/bloom-deepspeed-inference-fp16 --dtype float16 --batch_size 1
> ```
> 
> You'd need to be on this branch: [microsoft/DeepSpeed#2217](https://github.com/microsoft/DeepSpeed/pull/2217)
> 
> for int8 4x80 gpus should be enough, so you can do `--num_gpus 4`

@stas00 I am running my server without Internet available. How can I covert the checkpoints to int8 sharded one by myself? I’m also facing the error `NotImplementedError: Cannot copy out of meta tensor; no data! ` with the latest commit DeepSpeed from `ds-inference/ZeroQuant-Int8`.

2022-08-30 04:33 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
> @stas00 , I noticed that we are creating the dummy tensors using deepspeed.OnDevice(dtype=torch.float16) on line 167. Shouldn't we change this to int8 for qunatization?
> I m getting throughput = 89msec/token for 8 and 160msec/token for 8 and 4 GPUs respectively. Can this ^^ be the reason?

@RezaYazdaniAminabadi?

2022-08-30 04:38 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
> How can I covert the checkpoints to int8 sharded one by myself?

@pai4451, please see `save_mp_checkpoint_path` in @mayank31398's code (this PR)

2022-08-30 04:46 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
LOL @stas00 I dropped the caching functionality since I figured that no one would use it. Especially now, when Microsoft has provided the weights themselves.

2022-08-30 04:47 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
You might need to look back 3-4 commits @pai4451 
You want to look at cache_ds_checkpoints.py

2022-08-30 04:53 UTC, stas00 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
oh, I see, yes, we should leave it in place. Especially since eventually this will be no longer bloom-176b specific, so having the ability to generate small weights locally would be beneficial.

apologies if I wasn't clear in the first place, I was suggesting to add the support to the pre-sharded weights from the hub, but not dropping the original way.

so if possible please restore those? and of course we want to document that.

That's another way to approach it, is to add to README instead to how to pre-shard and save the weights - instead of having it implemented in the code.

Whatever you feel is more intuitive to you, @mayank31398

2022-08-31 03:52 UTC, pai4451 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
> This has been fixed. Was a bug in DeepSpeed. Thanks @RezaYazdaniAminabadi

@mayank31398 @stas00 Thanks, I can run the ZeroQuant int8 version of bloom now. But the output is repetitive, has it been fixed right now?
`in=DeepSpeed is a machine learning framework
out=DeeSpeed is a machine learning framework for deep deep deep deep deep deep deep deep deep deep deep…(repeated)`

My generate_kwargs are `max_new_tokens=100, do_sample=False`.
I installed the latest DeepSpeed from master branch and the versions are
`deepspeed==0.7.3+2Bafdc7287
transformers==4.20.1
accelerate==0.12.0`.

@mayank31398  Any changes did you make to fix this bug? Thanks in advance.

2022-08-31 04:26 UTC, mayank31398 commented on scripts/bloom-inference-server/README.md
> +python scripts/bloom-inference-server/cli.py --model_name bigscience/bloom --dtype fp16 --deployment_framework ds_inference --save_mp_checkpoint_path <PATH TO DS CACHED MODEL> --generate_kwargs '{"mi
No, are you on the latest commit (master branch) in DeepSpeed @pai4451 ?
Can you try a different input sentence?

2022-08-31 12:17 UTC, mayank31398 commented
@stas00 https://huggingface.co/bigscience/bloom/tree/main
Some changes were pushed to bigscience/bloom just 3 hours ago.
snapshot_download fails as a result of this change.
```
FileExistsError: [Errno 17] File exists: '../../../../blobs/c4072f2f02baee6f0d50739cf14439f61e0605913ed65606f9bcb11043838a2e' -> '/home/gpttest/nfs/mayank/HF_cache/models--bigscience--bloom/snapshots/874fa447d586d0a28ab66aa3ca49da43ae1ec0f6/tensorboard/main/events.out.tfevents.1649441015.jean-zay-iam50.156467.0
```
Any idea how to get around this?
Also, if this is fixed, would snapshot_download download the whole checkpoints again?
This would be highly impractical right?

2022-08-31 18:45 UTC, stas00 commented
tagging @thomasw21 who made the checkpoint update.

2022-08-31 19:08 UTC, stas00 commented
@mayank31398, please also note the renames in this commit https://github.com/microsoft/DeepSpeed/pull/2217/files/c77f5e0e385db405475b2842a6f5725c0f551170..f3f4b1dda9f9ba09042b8b63bbee475c9364bc56 in particular `s/mp_size/tp_size/`

this is now merged so we should update this side - you can just do a global search and replace on all of the files under scripts - or if you'd prefer I do that please let me know - don't want to step on your toes if you're still on the old DS branch.

2022-09-01 01:04 UTC, mayank31398 commented
Let me try updating to the latest HF_hub, and deepsped to see if that fixes things.

2022-09-01 04:17 UTC, mayank31398 commented
Nevermind, I have fixed this. This was a bug because all 8 processed in my DeepSpeed code were trying to download simultaneously

2022-09-01 04:51 UTC, stas00 commented
oddly enough It doesn't look like `mp_size` was renamed to `tp_size`, which is odd, so I only had to modify this line with the updated checkpoints:
```
checkpoints_json = os.path.join(repo_root, "ds_inference_config.json")
```

2022-09-01 15:36 UTC, stas00 commented
@mayank31398, would it be OK if we merged this PR - and then perhaps have another iteration of tweaks in subsequent PRs if needed? As we are renaming files I want the rename to be merged first before tweaking those.

You have the commit rights, so you can do the honours if you're in agreement.

Thank you!

2022-09-01 17:04 UTC, mayank31398 commented
Yes @stas00 , currently, MII is not working with DS-inference. But we can merge and I can continue to work on this.

2022-09-01 17:06 UTC, merged

2022-09-01 17:08 UTC, mayank31398 commented
Also, @stas00 there are some pieces of code that both the server folder and the scripts folder can share.
I will work on getting the reduntant code out once all the stuff in server stuff is fixed :)

2022-09-01 17:09 UTC, stas00 commented
perfect, then you can start a new PR once you have some new edits. We can just do it in iterations.