WIP: Prefix lm
bigscience-workshop/Megatron-DeepSpeed pull request #52
Opened 2021-08-05 14:46 UTC by thomasw21

Support for prefix-lm

2021-08-05 14:48 UTC, thomasw21 commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
This is questionable ... maybe we can rename gpt_model to something? Or just duplicate everything into a prefix lm model.

2021-08-05 15:01 UTC, sbmaruf commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
Is there any problem if you create a new argument in `get_language_model` with `is_prefix_lm` and pass it? In that way `AttnMaskType .causal` will not break and you just extend `prefix_lm` wherever necessary.

2021-08-05 15:05 UTC, thomasw21 commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
Well I'd say having a prefix and `AttnMaskType.causal` is just asking to have a bug.

2021-08-05 15:29 UTC, ontocord reviewed
This looks really good. I left some comments based on our conversation with the group.

2021-08-05 15:29 UTC, ontocord commented on pretrain_gpt.py
> +        prefix_indices = get_prefix_indices(tokens, tokenizer.eod, partial_prefix_indices = None)
Isn't there a case where we want to use some special token like "||" or "<eos>" to represent the end of the prefix? That could be a parameter, and then you can compute the indices that way.

2021-08-05 15:29 UTC, ontocord commented on megatron/text_generation_utils.py
> +from megatron.utils import get_masks_and_position_ids, unwrap_model
If we change this name we would need to make sure all references in the code changes too no? Or maybe we just create a new version called get_prefix_lm_masks_and_position_ids. If we want fold this code back into main megatron I think we might want backwards compatability?

2021-08-05 15:29 UTC, ontocord commented on megatron/text_generation_utils.py
> +    attention_mask, _, position_ids = get_masks_and_position_ids(tokens, tokenizer.eod, args.reset_position_ids,
Suprising that the loss_mask is not even used here!

2021-08-05 15:29 UTC, ontocord commented on megatron/utils.py
> +def get_masks_and_position_ids(
Recommend adding " loss_on_targets_only=True " as a parameter to match T5. See discussion here https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/21

2021-08-05 15:29 UTC, ontocord commented on megatron/utils.py
> +                if prefix_indices:
Per discussion, we should move this if statement up to be under the "if resetn_attention_mask:" statement.

2021-08-05 15:29 UTC, ontocord commented on megatron/utils.py
> +                    loss_mask[b, prev_index: prefix_indices[b][j]] = 0.0
Should add "if loss_on_targets_only: loss_mask[..."

2021-08-05 15:29 UTC, ontocord commented on megatron/utils.py
> +        assert partial_prefix_indices is None or len(partial_prefix_indices[batch_id]) == len(eod_indices), f"The number of prefixes has to match the number of documents. Got {len(partial_prefix_indi
This means that you would need a prefix indice for each eod. Would you ever have the case where you don't have an prefix_indice for some eod. I suppose that prefix_indice would be 0? If so we should document that.

2021-08-05 15:29 UTC, ontocord commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
Also, we should have an option that is set for prefix_lm_type which could be "prefix_across_documents", or "prefix_per_document", per discussion.

2021-08-05 15:29 UTC, ontocord commented on megatron/utils.py
> +                if prefix_indices:
Also if prefix_lm_type is "prefix_across_documents" we would not do this masking here.

2021-08-05 15:37 UTC, thomasw21 commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
I think using reset_attention_mask is a good way to do so.

2021-08-05 15:42 UTC, thomasw21 commented on pretrain_gpt.py
> +        prefix_indices = get_prefix_indices(tokens, tokenizer.eod, partial_prefix_indices = None)
> Isn't there a case where we want to use some special token like "||" or "" to represent the end of the prefix? That could be a parameter, and then you can compute the indices that way.

I think this is what will happen in labeled data, ie in prompts we used "|||" to seperate prompts from targets. We should create a function that computes the prefix_indices in this case. (maybe we don't need the partial_prefix_indices and directly compute from data)

> Also, where prefix_lm_type is "prefix_across_documents", you would instead compute a prefix_across_documents_indices of the same batch size as tokens? And either the indice is set to random or designated by some token?

Yes, essentially instead of having a List[List[int]] you would have List[int]. Or we can hack our way in by saying we have a a single document in the sequence, and thus keep the List[List[int]] framework.

2021-08-05 15:43 UTC, thomasw21 commented on megatron/text_generation_utils.py
> +from megatron.utils import get_masks_and_position_ids, unwrap_model
Yeah you can do so in Pycharm by refactoring code. I'm okay with reverting back my change, I initially thought `ltor` meant lower triangular something which is why I changed that.

2021-08-05 15:44 UTC, ontocord commented on megatron/utils.py
> +                        loss_mask[b, prev_index: prefix_indices[b][j]] = 0.0
I also question if there is anything after the last <eod>. If it's more document text, then we could still train on it. But if it's undefined or something like <eos>, do we need to mask the loss for those tokens?

2021-08-05 15:44 UTC, ontocord commented on pretrain_gpt.py
> +        prefix_indices = get_prefix_indices(tokens, tokenizer.eod, partial_prefix_indices = None)
At some point, if the modeling group wants to pass in the prefix_indices as part of the data batch, we would need to load that into partial_prefix_indices and check, correct?

Also per @sbmaruf discussion, we may at some later date want to do multiple prefix for one target. Then the prefix_indices would no longer be an array or array of int I think. But no need to impelment now. Just to keep in mind.

2021-08-05 15:48 UTC, thomasw21 commented on megatron/text_generation_utils.py
> +    attention_mask, _, position_ids = get_masks_and_position_ids(tokens, tokenizer.eod, args.reset_position_ids,
Hum I don't actually know that part of the code. My guess is this is pure inference? and that each document is really only one sequence?

2021-08-05 15:48 UTC, ontocord commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
Ah, ok. Then that would mean we always have a prefix in the case of reset_attention_mask is False correct? Or if we don't want a prefix, then the prefix_across_documents_indices would have a 0 in the particular batch?

2021-08-05 15:49 UTC, ontocord commented on megatron/text_generation_utils.py
> +from megatron.utils import get_masks_and_position_ids, unwrap_model
Yeah, it should have been left_to_right!

2021-08-05 15:55 UTC, thomasw21 commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
IMO we can manage with:
 - `--prefix-lm --reset-attention-mask` to be per document prefix
 - `--prefix-lm` to be cross document prefix
 
 If you don't want prefix,  you can just not put `--prefix-lm` and it'll be natural gpt.

2021-08-05 15:58 UTC, thomasw21 commented on pretrain_gpt.py
> +        prefix_indices = get_prefix_indices(tokens, tokenizer.eod, partial_prefix_indices = None)
Depends on how people want to see it:
 - if multiple prefix are processed independently of one another, then yeah we need something better
 - if we don;t care, we can just concatenant all prefix together to obtain a single meta prefix. I think?

2021-08-05 16:02 UTC, thomasw21 commented on megatron/utils.py
> +        assert partial_prefix_indices is None or len(partial_prefix_indices[batch_id]) == len(eod_indices), f"The number of prefixes has to match the number of documents. Got {len(partial_prefix_indi
So prefix_indice would be None. If it's 0 it's causal masking.

2021-08-05 16:03 UTC, thomasw21 commented on megatron/utils.py
Yeah something along those lines!

2021-08-05 16:04 UTC, thomasw21 commented on megatron/utils.py
> +                        loss_mask[b, prev_index: prefix_indices[b][j]] = 0.0
Yeah it's in the TODOs, I don't know, I'd expect that it;s a partial document so we can do it IMO.

2021-08-05 16:12 UTC, thomasw21 commented on megatron/utils.py
> +def get_masks_and_position_ids(
I thought `loss_on_targets_only=False` on T5?

2021-08-05 17:41 UTC, ontocord commented on megatron/model/gpt_model.py
> +            encoder_attn_mask_type=AttnMaskType.prefix if args.prefix_lm else AttnMaskType.causal,
I think that's a good solution. We just need to document `--reset-attention-mask `means per document prefix.

2021-08-05 17:43 UTC, ontocord commented on pretrain_gpt.py
> +        prefix_indices = get_prefix_indices(tokens, tokenizer.eod, partial_prefix_indices = None)
Ok. Let's leave the multi-prefix issue for later. We can leave this as comments in the code too if need be for future impelmentors?

2021-08-05 17:44 UTC, ontocord commented on megatron/utils.py
> +def get_masks_and_position_ids(
Yes. I meant that the variable name is `loss_on_targets_only` in T5. I think we do want to default to True for our case though. But I could be wrong.

2021-08-05 17:44 UTC, ontocord commented on megatron/utils.py
> +        assert partial_prefix_indices is None or len(partial_prefix_indices[batch_id]) == len(eod_indices), f"The number of prefixes has to match the number of documents. Got {len(partial_prefix_indi
Yes. 0 means regular autoregresive causual masking.

2021-08-05 17:46 UTC, ontocord commented on megatron/utils.py
> +                        loss_mask[b, prev_index: prefix_indices[b][j]] = 0.0
OK. I think this is resolved right, per our conversation. There are paddings to the right, but they are all `<eod>` and you can set the --eod-mask-loss flag and ignore those pads.

2021-08-05 18:00 UTC, thomasw21 commented on megatron/utils.py
> +                        loss_mask[b, prev_index: prefix_indices[b][j]] = 0.0
Sorry I might not have been clear:
 - Pretraining: it's partial documents
 - Text generation: it's padding

2021-08-05 20:38 UTC, ontocord reviewed
I provided some options to add prefix_separator_token and some added comments/documentations.

2021-08-05 20:38 UTC, ontocord commented on megatron/arguments.py
> +    group.add_argument('--loss-on-targets-only', action='store_true',
For reset-attention-mask parameter, I recommend adding a note that says 
```

    group.add_argument('--reset-attention-mask', action='store_true',
                       help='Reset self attention maske after '
                       'end-of-document token. If running in --prefix-lm, then this will set per-document prefixing.')
```

2021-08-05 20:38 UTC, ontocord commented on megatron/arguments.py
> +    group.add_argument('--prefix-lm', action="store_true", help="Use prefix mask on attention matrices.")
recommend adding more comments:
`
 group.add_argument('--prefix-lm', action="store_true", help="Use prefix mask on attention matrices. if  used with --reset-attention-mask then prefixing will be per document. Otherwise prefixing will be per microbatch. ")`

2021-08-05 20:38 UTC, ontocord commented on megatron/utils.py
> +def get_prefix_indices(data, eod_token, partial_prefix_indices, reset_attention_mask):
recommend adding `prefix_seprator_token = None `as a parameter.  And this could be an argument (you would need to get the token from the vocab for "|||" for example.

2021-08-05 20:38 UTC, ontocord commented on megatron/utils.py
> +
recommend

```
assert prefix_seperator_token is None or partial_prefix_indices is None, "if a prefix_separator_token is set, no partial_prefix_indices should provided"

assert prefix_seperator_token is not None  and  reset_attention_mask, "prefix_separator_token is per document and must be used with the reset_attention_mask parameter"

if prefix_seperator_token is not None:
  partial_prefix_indices = (data[batch_id] == prefix_seperator_token).nonzero() # not sure what the squeeze(-1) is for in the case of eod_indices.
```

2021-08-05 20:38 UTC, ontocord commented on pretrain_gpt.py
> +            reset_attention_mask=args.reset_attention_mask
recommend passing in prefix_separator_token = args.prefix_separator_token

2021-08-05 20:38 UTC, ontocord commented on megatron/arguments.py
> +    group.add_argument('--prefix-lm', action="store_true", help="Use prefix mask on attention matrices.")
Also recommend 
`
group.add_argument('--prefix_separator_token', type=int, required=False, help="The token id for the prefix separator. Must be used with --prefix_lm and  --reset-attention-mask ")`

2021-08-06 11:14 UTC, thomasw21 commented on pretrain_gpt.py
> +    assert args.prefix_lm is False, "Use `pretrain_prefix_lm.py` instead"
I decided to duplicate since there's a weird prefix optimization that was hidden that I initially did not see. https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/pretrain_gpt.py#L56-L71

This made me think that sharing code is very risky, as my initial test were running, so I though masking was correct, until I discovered this while trying to compute some tests.

IMO code duplication is much better than the wrong abstraction.

2021-08-06 11:17 UTC, thomasw21 commented on megatron/arguments.py
> +    group.add_argument('--loss-on-targets-only', action='store_true',
I think we can improve while being less verbose. Something along the lines that "token interactions are document constrained in self attention mask"

2021-08-06 11:21 UTC, thomasw21 commented on megatron/arguments.py
> +    group.add_argument('--prefix-lm', action="store_true", help="Use prefix mask on attention matrices.")
1) Hum I'm not a fan of documenting combination of arguments ... I'll think about it.

2) Let's not focus on this token seperator just yet. I don;t think we're running anything else than pretraining. Once we do I'll try to plug it in. However I agree that the help needs to inform on other arguments in this case ...

2021-08-06 11:24 UTC, ontocord commented on pretrain_gpt.py
> +    assert args.prefix_lm is False, "Use `pretrain_prefix_lm.py` instead"
Thanks for sharig this!

2021-08-06 11:25 UTC, thomasw21 commented on megatron/utils.py
> +def get_prefix_indices(data, eod_token, partial_prefix_indices, reset_attention_mask):
Let's not do that just yet. Reason is that I don't know yet how we'll work with prompts. Otherwise yes I agree with need a parser to find those partial indices (I assumed we would get them in preprocessing or whatever), but if not, we might need to compute them here.

2021-08-06 11:25 UTC, thomasw21 commented on megatron/utils.py
> +
Not yet.

2021-08-06 11:25 UTC, thomasw21 commented on pretrain_gpt.py
> +            reset_attention_mask=args.reset_attention_mask
Not yet.

2021-08-06 11:27 UTC, thomasw21 commented on megatron/model/gpt_model.py
> +            # TODO: Change naming of class from GPT to something that encapsulate prefix lm.
As mentioned previously, I think naming this class GPT is wrong. Can we obtain a better naming? Something like autoregressive maybe? Basically an abstraction of both gpt and prefix-lm

2021-08-09 08:52 UTC, thomasw21 commented on megatron/arguments.py
> +    group.add_argument('--loss-on-targets-only', action='store_true',
Okay my opinion after thinking about it:
 - either we rename `--reset-attention-mask` to something like `--document-specific-attention` and add a comment that documents are independent from one another (using eod token as a document segmenter)
 - either we change the help function to say something like `Documents, segmented using eod tokens, are considered independent. Attention between tokens from different documents have a null score.`
 
 The reason why I like these versions better is to force orthogonalisation of features, ie those flags (prefix and reset attention) have to be independent from one another. Otherwise if you end up adding something else on the attention mechanism whenever have to add a note in the help

2021-08-09 08:53 UTC, thomasw21 commented on megatron/arguments.py
> +    group.add_argument('--prefix-lm', action="store_true", help="Use prefix mask on attention matrices.")
1. See comment above.

2021-08-09 09:16 UTC, thomasw21 commented
Up for review, some notable changes:
 - we seperate pretraining scripts as there was some optimization done in `pretrain_gpt.py` that prevented prefix lm from working correctly. https://twitter.com/BonzoESC/status/442003113910603776?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E442010383725760512%7Ctwgr%5E%7Ctwcon%5Es2_&ref_url=https%3A%2F%2Fsandimetz.com%2Fblog%2F2016%2F1%2F20%2Fthe-wrong-abstraction
 - tests are on a seperate PR https://github.com/thomasw21/Megatron-DeepSpeed/pull/1
 - removed `--prefix-lm` flag as we can determine this from the pretraining script used.
 
 What I think we shouldn't do in this PR:
 - start thinking about how the evaluation is going to work: I'll rename this PR to show we're working on a pretrain specific work. The problem with evaluation is I don't think anyone has been working on such a script even for GPT. So I'd much rather we get a clear idea on how it would work in GPT and then adapt it. Typically it might not be done on Megatron-DeepSpeed at all for what we know. For me there are just too many uncertainties in order to integrate those changes in this PR.
 
 cc @ontocord @sbmaruf

2021-08-10 11:57 UTC, sbmaruf commented
@thomasw21 Great minimal implementation. I liked it. Haven't got the time for doing a through (running, debugging with special cases) review but till now, LGTM. 
One comment,
- I understand you implement it by iterative method. Do you think it's possible to convert it to a matrix operations instead of  loop? Does iterative implementation makes it slower or Megatron implements this processing in parallel. Meaning it preprocess data in a `multi-thread/process` along with the training. In that case I don't think we need to implement the processing using matrix operation.

2021-08-10 12:18 UTC, thomasw21 commented
> * I understand you implement it by iterative method. Do you think it's possible to convert it to a matrix operations instead of  loop? Does iterative implementation makes it slower or Megatron implements this processing in parallel. Meaning it preprocess data in a `multi-thread/process` along with the training. In that case I don't think we need to implement the processing using matrix operation.

I don't actually know, we can probable optimize some code (ie get at least the row specific prefix working as matrix), and perhaps some optimization on the other one. I'd be curious to benchmark this before going further. My main intuition is that current setup is bound by gpu usage, that processing is already done in multi process setup (I doubt that a single process in loading all batches sequentially), so optimising this flow wouldn't return much. (NOT TESTED, JUST MY INTUITION)

2021-08-11 02:06 UTC, ontocord commented
I recall that the original code was iterative too, so we aren't any slower than the base megatron pretrain code, @sbmaruf.  Great work @thomasw21

2021-09-07 08:38 UTC, ibeltagy requested changes
Thanks, @thomasw21 for the PR. 
The main change request is to remove the `pretraine_prefix_lm` file and reuse `pretrain_gpt` to avoid large blocks of duplicate code which can cause all kinds of problems. 
I didn't review `get_ltor_masks_and_position_ids` and `get_prefix_indices` yet. I will review them later. 
Thanks.

2021-09-07 08:38 UTC, ibeltagy commented on megatron/arguments.py
> +    group.add_argument('--loss-on-targets-only', action='store_true',
Add an argument here to enable/disable prefix-lm

2021-09-07 08:38 UTC, ibeltagy commented on megatron/model/gpt_model.py
> +        prefix_lm=False,
pass `prefix_lm` using `args` instead

2021-09-07 08:38 UTC, ibeltagy commented on megatron/model/gpt_model.py
> +        prefix_lm=False
same, use args.

2021-09-07 08:38 UTC, ibeltagy commented on megatron/utils.py
> +def get_ltor_masks_and_position_ids(
I didn't review `get_ltor_masks_and_position_ids` and `get_prefix_indices` yet.

2021-09-07 09:13 UTC, thomasw21 commented on pretrain_prefix_lm.py
> +# coding=utf-8
I initially did what you had in mind. However while writing some tests some things did behave correctly due to some deep speed optimization I believe. There was a comment about it earlier in the PR.

https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/52#discussion_r684154051

2021-09-15 14:07 UTC, ibeltagy requested changes

2021-09-15 14:07 UTC, ibeltagy commented on megatron/utils.py
> +                attention_mask[b, 0, :prefix_indices[b], :prefix_indices[b]] = 1
just to make sure I understand, do you have one prefix index per batch or one prefix index per instance?

2021-09-15 14:49 UTC, thomasw21 commented on megatron/utils.py
> +                    loss_mask[b, :prefix_indices[b]] = 0.0
I'm not exactly sure what you mean. I might have forgotten to add `if reset_position_ids or reset_attention_mask or prefix_indices is not None` if that what's you mean.

2021-09-15 14:59 UTC, thomasw21 commented on megatron/utils.py
> +
After thinking about it, this should be a fairly generic mechanism. Ie even when `reset_attention_mask` is False, then it should be 'equivalenet" to adding and eod at the end. I'll work towards a refactor.

2021-09-15 19:30 UTC, ibeltagy commented on megatron/utils.py
> +                    loss_mask[b, :prefix_indices[b]] = 0.0
yes, that also works.

2021-09-15 19:37 UTC, ibeltagy commented on megatron/utils.py
> +
True. It is equivalent but not needed.

2021-09-15 19:41 UTC, ibeltagy commented on megatron/utils.py
> +                attention_mask[b, 0, :prefix_indices[b], :prefix_indices[b]] = 1
In the `reset_attention_mask is False` case, the way I am reading it is that the size of the attention mask is one mask per batch (not per row), check here https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/28a712d42e071c50686a9a2eb4f1816dcdb0ef82/megatron/utils.py#L173
you see that mask shape is `[1, 1, seqlen, seqlen]`. 
So here https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/28a712d42e071c50686a9a2eb4f1816dcdb0ef82/megatron/utils.py#L235, this line shouldn't work because `b` can be greater than 1.

2021-09-16 06:10 UTC, thomasw21 commented on megatron/utils.py
> +
Okay dropping refactor right now then.

2021-09-16 06:18 UTC, thomasw21 commented on megatron/utils.py
> +                attention_mask[b, 0, :prefix_indices[b], :prefix_indices[b]] = 1
Ah nice catch ! So I'm pretty sure we want to remove the logic here

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/28a712d42e071c50686a9a2eb4f1816dcdb0ef82/megatron/utils.py#L170-L173

Essentially I'd say this is an optimisation as the masking is batch size independent in gpt, but would be batch size dependent in prefix lm? We can also work with batch size independent also I guess, sampling a single prefix id for the whole batch. WDYT?

2021-09-16 11:03 UTC, ibeltagy commented on megatron/utils.py
> +                attention_mask[b, 0, :prefix_indices[b], :prefix_indices[b]] = 1
I am fine with a single prefix index per batch.

2021-09-16 11:52 UTC, thomasw21 commented on megatron/utils.py
> +                attention_mask[b, 0, :prefix_indices[b], :prefix_indices[b]] = 1
Hum this made the prefix row dependent, https://github.com/thomasw21/Megatron-DeepSpeed/commit/0cdb0a941ddeefbdb1ccab3598f1e34bb38c35a3 . 

Do you have insights as to why one would work better than the other?

2021-09-16 11:53 UTC, thomasw21 commented
Btw I've merged the set of tests here https://github.com/thomasw21/Megatron-DeepSpeed/commit/295e8d0ddd3716d09679571059823e4b862bbcc2

There are some unrelated tests (rotary and gpt). Feel free to disregard as they are tests (which means if they pass good, if they don't we should look inot it)

2021-09-16 11:58 UTC, ibeltagy commented on megatron/utils.py
> +                attention_mask[b, 0, :prefix_indices[b], :prefix_indices[b]] = 1
being row dependent is better assuming it doesn't increase time and memory that much

2021-09-16 12:02 UTC, thomasw21 commented on megatron/utils.py
> +                attention_mask[b, 0, :prefix_indices[b], :prefix_indices[b]] = 1
Okay let's keep this as is, and monitor is we're much slower compared to gpt. Bear in mind:
 - prefix lm is not using a custom cuda kernel anymore, so some loss in time/memory is expected

Maybe we can test on a 350m version and then switch if we think have a single index might be faster?

2021-09-16 15:22 UTC, ibeltagy commented
>  kept the pretrain_prefix script separate

ok. Can you confirm that it still matches the `pretrain_gpt` script before merging?

> Maybe we can test on a 350m version and then switch if we think have a single index might be faster?

The larger the model the more realistic the time estimates are. Let's just start the 1.3B model and see how it goes. We can stop it early if it doesn't seem promising.

2021-09-16 15:22 UTC, ibeltagy approved these changes

2021-09-16 16:04 UTC, thomasw21 commented
> ok. Can you confirm that it still matches the pretrain_gpt script before merging?

Well it doesn't match because there are some prefix lm specific code (generating prefix for example) and removing some gpt specific code

Running `diff pretrain_gpt.py pretrain_prefix_lm.py` returns the following:
```
36d35
< 
53c52,53
<                 parallel_output=True
---
>                 parallel_output=True,
>                 prefix_lm=True
59,75d58
<             # Precompute the attention mask and store it in args. This avoids having to
<             # pipeline it as an activation during training. The mask is constant, and thus
<             # we can reuse it.
<             attention_mask = torch.tril(torch.ones(
<                 (1, args.seq_length, args.seq_length), device=torch.cuda.current_device())).view(
<                     1, 1, args.seq_length, args.seq_length)
< 
<             # Convert attention mask to binary:
<             attention_mask = (attention_mask < 0.5)
<             if args.fp16:
<                 attention_mask = attention_mask.half()
<             elif args.bf16:
<                 attention_mask = attention_mask.bfloat16()
< 
<             # must be bool or the training crashes expecting bool, but getting Half
<             args.attn_mask = attention_mask.to(torch.bool)
< 
81c64,65
<                 post_process=post_process
---
>                 post_process=post_process,
>                 prefix_lm=True
107a92,99
>     # Prefix
>     prefix_indices = get_prefix_indices(
>         tokens,
>         tokenizer.eod,
>         partial_prefix_indices=None,
>         reset_attention_mask=args.reset_attention_mask
>     )
> 
115c107
<         prefix_indices=None,
---
>         prefix_indices=prefix_indices,
121d112
< 
138a130,137
>     # Prefix
>     prefix_indices = get_prefix_indices(
>         tokens,
>         tokenizer.eod,
>         partial_prefix_indices=None,
>         reset_attention_mask=args.reset_attention_mask
>     )
> 
146c145
<         prefix_indices=None,
---
>         prefix_indices=prefix_indices,
150,151c149
<     return (tokens, position_ids, attention_mask), (labels, loss_mask)
< 
---
>     return (tokens, position_ids, attention_mask), (labels, loss_mask), prefix_indices
199d196
< 
204d200
< 
```

> The larger the model the more realistic the time estimates are. Let's just start the 1.3B model and see how it goes. We can stop it early if it doesn't seem promising.

Ok

2021-09-16 16:08 UTC, merged

2021-09-16 17:46 UTC, stas00 commented
The CI failed 4 tests:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/runs/3623547090?check_suite_focus=true

```
=========================== short test summary info ============================
ERROR tests/test_model.py::MyTestCase::test_gpt - ModuleNotFoundError: No mod...
ERROR tests/test_model.py::MyTestCase::test_gpt_rotary_embeddings - ModuleNot...
ERROR tests/test_model.py::MyTestCase::test_prefix_lm_reset_attention_mask - ...
ERROR tests/test_model.py::MyTestCase::test_prefix_lm_wo_reset_attention_mask
```

why was it merged with the errors?

2021-09-16 17:47 UTC, stas00 commented
I think the github actions is showing the wrong to the CI reports, I had to manually find it via Actions.

2021-09-16 18:37 UTC, stas00 commented
I'll disable these tests for now, so that the test suite can be used for testing other PRs.

One note though: it fails with `ModuleNotFoundError: No module named 'mpi4py'` - but this means that the test wasn't set up properly. We do not want `mpi4py` in the dependencies, as it'd swipe the problems under the carpet. 

Please use t`est_training.py` as a model to copy from on how to setup a multi-gpu testing.

2021-09-16 18:41 UTC, thomasw21 commented
Yeah I saw, I'll fix this. I have to use an alternative method to `test_training` as I want to freely manipulate the model, ie in order to check some invariants.

Thank you for noticing!

2021-09-16 18:42 UTC, stas00 commented
ok, so I won't add the skipping then, if you're taking care of it. Thank you, Thomas!

2021-09-16 18:48 UTC, stas00 commented
And I know what you mean though. It's much harder to access internal data using the launcher approach.

Perhaps using a single GPU then? This is how we do it on transformers for all basic tests and then no launcher/mpi is needed.

2021-09-16 18:56 UTC, thomasw21 commented
Hum yes it is, but I'm trying to reproduce the error right now (I might have an outdated version of deepspeed) with little success.

2021-09-16 19:06 UTC, stas00 commented
`pip uninstall mpi4py -y`?

2021-09-16 19:14 UTC, thomasw21 commented
![image](https://user-images.githubusercontent.com/24695242/133671419-698ca0b3-4d26-42bd-9bb9-0ab9d5c906d8.png)

I don;t have `mpi4py`. I'm running test on JZ and the only ones that are failing for me are activations one. 

```
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/test_activations.py::TestActivations::test_geglu - AttributeErro...
FAILED tests/test_activations.py::TestActivations::test_liglu - AttributeErro...
FAILED tests/test_activations.py::TestActivations::test_reglu - AttributeErro...
FAILED tests/test_activations.py::TestActivations::test_swiglu - AttributeErr...
============= 4 failed, 11 passed, 14 warnings in 70.07s (0:01:10) =============
```

```
AttributeError: module 'torch.testing' has no attribute 'assert_close'
```

2021-09-16 19:21 UTC, stas00 commented
perhaps you're using 1 gpu setup and thus deepspeed not trying to solve the multi-gpu env automatically.

> AttributeError: module 'torch.testing' has no attribute 'assert_close'

yickes. Back compat issue as they dropped assert_equal in pt-1.9, I will move it into our testing.py and make sure it works with any pt version.

2021-09-16 21:39 UTC, stas00 commented
> -- Docs: https://docs.pytest.org/en/stable/warnings.html
> =========================== short test summary info ============================
> FAILED tests/test_activations.py::TestActivations::test_geglu - AttributeErro...
> FAILED tests/test_activations.py::TestActivations::test_liglu - AttributeErro...
> FAILED tests/test_activations.py::TestActivations::test_reglu - AttributeErro...
> FAILED tests/test_activations.py::TestActivations::test_swiglu - AttributeErr...
> ============= 4 failed, 11 passed, 14 warnings in 70.07s (0:01:10) =============
> ```
> 
> ```
> AttributeError: module 'torch.testing' has no attribute 'assert_close'
> ```

Fixed in https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/106