WIP: Implement rotary embeddings
bigscience-workshop/Megatron-DeepSpeed pull request #7
Opened 2021-07-21 18:32 UTC by thomasw21

Fixes: https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/6

Mostly copy work already done from EleutherAI (I've left a link at the top of `positional_embeddings.py`).

It slightly differs from the paper implementation. In particular, it permutes the ordering of the dimension in order to have an easier to compute rotary matrix multiplication.

Also:
 - I've slightly modified the caching mechanism for positional embeddings.

2021-07-23 17:56 UTC, TevenLeScao requested changes

2021-07-23 17:56 UTC, TevenLeScao commented on megatron/arguments.py
> +    required_args = ['num_layers', 'hidden_size', 'num_attention_heads', 'position_embedding_type']
can we make embedding type absolute by default ? keeps backwards compatibility, also this way we don't have to retroactively change every single script!

2021-07-23 17:56 UTC, TevenLeScao commented on megatron/arguments.py
> +    if args.position_embedding_type == PositionEmbeddingType.absolute:
think that thanks to this block we can just remove both `max_position_embeddings` and `embedding_type` from the required args

2021-07-23 17:56 UTC, TevenLeScao commented on megatron/arguments.py
> +    group.add_argument('--max-absolute-position-embeddings', type=int, default=None,
not a fan of changing the argument name; let's keep it the same to have backward compatibility, it's fine if it only applies to one embedding type

2021-07-23 17:56 UTC, TevenLeScao commented on megatron/model/fused_softmax.py
> +from megatron.enums import AttnMaskType
This move surprises me. Did you move `enums` up a folder and if so, why?

2021-07-23 22:05 UTC, thomasw21 commented on megatron/model/fused_softmax.py
> +from megatron.enums import AttnMaskType
Basically this caused circular dependency, when I added my enum in that file, and imported it in `arguments.py`. The reason why, is when you import `from megatron.model.enums import AttnMaskType` you'd execute `megatron/model/__init__.py` which means you're importing a bunch of code, some of which import `arguments.py`.
https://stackoverflow.com/questions/24302754/python-submodule-imports-using-init-py/24303380

In order to remove this dependency I've moved enums outside model, as it's safe to say that importing enums should not be linked to model. Please see the section `Changes` in the PR description.

2021-07-23 22:11 UTC, thomasw21 commented on megatron/arguments.py
> +    required_args = ['num_layers', 'hidden_size', 'num_attention_heads', 'position_embedding_type']
`position_embedding_type` is kept as it can't be None.

2021-07-23 22:11 UTC, thomasw21 commented on megatron/arguments.py
> +    if args.position_embedding_type == PositionEmbeddingType.absolute:
See previous remark

2021-07-27 15:40 UTC, TevenLeScao approved these changes

2021-07-27 18:31 UTC, thomasw21 commented on megatron/model/positional_embeddings.py
> +def apply_rotary_pos_emb(q, k, cos, sin, offset: int = 0):
So I'm not familiar with `torch.jit.script` but I guess it compiles it? I admit that the code was copy pasted from EleutherAI with some little modifications. I'm okay with removing this helper if you want.

2021-07-28 16:48 UTC, merged

2021-09-10 21:47 UTC, stas00 commented
This broke the possibility to load our checkpoints into Megatron-LM or original Megatron-Deepspeed because they don't have `megatron.enum` and `torch.load` breaks.

Would it be possible to restore it to how it was?